version: '2.2'

services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    container_name: app_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./.test.env
    depends_on:
      - db
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/static
    networks:
      - app_net

  db:
    image: postgres:11
    container_name: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.test.env
    ports:
      - 5435:5432
    networks:
      - app_net

  nginx:
    image: nginx:mainline-alpine
    container_name: app_nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/static
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    networks:
      - app_net

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: app_frontend
    env_file:
      - ./.test.env
    depends_on:
      - backend
    expose:
      - 8080
    volumes:
      - node_modules:/app/node_modules
    networks:
      - app_net

volumes:
  postgres_data:
  static_volume:
  node_modules:

networks:
  app_net:
    driver: bridge